/* automatically generated by rust-bindgen 0.71.1 */

unsafe extern "C" {
    pub fn bitmap_get(
        bm: *mut ::std::os::raw::c_void,
        ii: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn bitmap_put(
        bm: *mut ::std::os::raw::c_void,
        ii: ::std::os::raw::c_int,
        vv: ::std::os::raw::c_int,
    );
}
